server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: history-service
          uri: lb://history-service
          predicates:
            - Path=/history/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
